version: "3.8"

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: stock_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dino2711
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  data_ingestion:
    build: .
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db
      DB_NAME: stock_data
      DB_USER: postgres
      DB_PASSWORD: dino2711

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  postgres_data:
